name: GitHub Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build for Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o terminal-logos-linux-amd64

      - name: Build for Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -o terminal-logos-linux-arm64

      - name: Build for macOS AMD64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o terminal-logos-macos-amd64

      - name: Build for macOS ARM64 (Apple Silicon)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o terminal-logos-macos-arm64

      - name: Build for Windows AMD64
        run: |
          GOOS=windows GOARCH=amd64 go build -o terminal-logos-windows-amd64.exe

      - name: Build for Windows ARM64
        run: |
          GOOS=windows GOARCH=arm64 go build -o terminal-logos-windows-arm64.exe

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            terminal-logos-linux-amd64
            terminal-logos-linux-arm64
            terminal-logos-macos-amd64
            terminal-logos-macos-arm64
            terminal-logos-windows-amd64.exe
            terminal-logos-windows-arm64.exe
          generateReleaseNotes: true